# Generated by Django 4.0.1 on 2022-06-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0016_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
